Add badges, cleanup spacing

diff --git a/create_django_project b/create_django_project
--- a/create_django_project
+++ b/create_django_project
@@ -2,7 +2,7 @@
 
 #########################################################
 #   Opiniated Django Project creator script
-#	by Eric Schultz <eric.schultz@cyvon.com>
+#   by Eric Schultz <eric.schultz@cyvon.com>
 #########################################################
 # This script creates a Django project with a bunch of
 #  additional "stuff" to make it much easier to work on
@@ -13,35 +13,35 @@
 # Take a look at the README for more info
 
 show_usage(){
-	echo "Usage: $0 <project name> <appname>"
-	exit 1
+    echo "Usage: $0 <project name> <appname>"
+    exit 1
 }
 
 if [ "X$1" == "X" ] ; then
-	show_usage
-	fi
+    show_usage
+    fi
 if [ "X$2" == "X" ] ; then
-	show_usage
-	fi
+    show_usage
+    fi
 
 pname=$1
 appname=$2
 
 if [[ ! "$pname" =~ ^[a-z][a-z0-9]+[a-z]$ ]]; then
-	echo "ERROR: Project name is not Kubernetes & Django Module Valid."
-	echo " - contain no more than 253 characters. "
-	echo " - contain only lowercase alphanumeric characters"
-	echo " - start and end with an alpha character."
-	echo " "
-	show_usage
+    echo "ERROR: Project name is not Kubernetes & Django Module Valid."
+    echo " - contain no more than 253 characters. "
+    echo " - contain only lowercase alphanumeric characters"
+    echo " - start and end with an alpha character."
+    echo " "
+    show_usage
 fi
 if [[ ! "$appname" =~ ^[a-z][a-z0-9\_]+[a-z]$ ]]; then
-	echo "ERROR: App name is not a valid Django Package Name."
-	echo " - contain no more than 253 characters. "
-	echo " - contain only lowercase alphanumeric characters, '_'"
-	echo " - start and end with an alphanumeric character."
-	echo " "
-	show_usage
+    echo "ERROR: App name is not a valid Django Package Name."
+    echo " - contain no more than 253 characters. "
+    echo " - contain only lowercase alphanumeric characters, '_'"
+    echo " - start and end with an alphanumeric character."
+    echo " "
+    show_usage
 fi
 
 export CREATE_HELM_CHART=1
@@ -52,7 +52,7 @@ export GITLAB_HOST="https://my_gitlab.host.com"
 export GITLAB_USER="my.gitlab.username"
 export GITLAB_API_TOKEN="gitlab_api_token"
 
-export DJANO_VER=3	# 1 or 2 for latest of that version, point release for specific ver
+export DJANGO_VER=3 # 1 or 2 for latest of that version, point release for specific ver
 # Note: For the docker images below, we use the -alpine version automatically
 export PYTHON_VER=3.9
 export POSTGRES_VER=13.2.0
@@ -69,12 +69,12 @@ cwd=`pwd`
 echo "Creating"
 docker pull $BUILDER_IMAGE
 docker run --privileged \
-	-v "$cwd/$pname":"/dest/$pname" \
-	-v "`realpath ~`/.gitconfig":"/root/.gitconfig" \
-	-v "`realpath ~`/.git-credentials":"/root/.git-credentials" \
-	-e ID_UID=`id -u` -e ID_GID=`id -g` \
-	-e CREATE_HELM_CHART -e CREATE_GITLAB_PROJECT -e GITLAB_STORE_CREDS -e GITLAB_HOST -e GITLAB_USER -e GITLAB_API_TOKEN -e PYTHON_VER -e POSTGRES_VER -e NGINX_VER -e REDIS_VER \
-	$BUILDER_IMAGE $1 $2 >$pname.create.log 2>&1
+    -v "$cwd/$pname":"/dest/$pname" \
+    -v "`realpath ~`/.gitconfig":"/root/.gitconfig" \
+    -v "`realpath ~`/.git-credentials":"/root/.git-credentials" \
+    -e ID_UID=`id -u` -e ID_GID=`id -g` \
+    -e CREATE_HELM_CHART -e CREATE_GITLAB_PROJECT -e GITLAB_STORE_CREDS -e GITLAB_HOST -e GITLAB_USER -e GITLAB_API_TOKEN -e PYTHON_VER -e POSTGRES_VER -e NGINX_VER -e REDIS_VER \
+    $BUILDER_IMAGE $1 $2 >$pname.create.log 2>&1
 
 
 # All Done, Print a nice message
diff --git a/image/opc_create b/image/opc_create
--- a/image/opc_create
+++ b/image/opc_create
@@ -1,21 +1,21 @@
 #!/bin/sh
 
 for i in helm docker sed; do 
-	if !  which $i >/dev/null ; then
-		echo "Error: $i missing"
-		exit 1
-	fi
+    if !  which $i >/dev/null ; then
+        echo "Error: $i missing"
+        exit 1
+    fi
 done
 
 if [ "X$1" = "X" ] ; then
-	echo "Usage: $0 <Project Name> <App Name>"
-	exit 1
-fi       
+    echo "Usage: $0 <Project Name> <App Name>"
+    exit 1
+fi
 
 if [ "X$2" = "X" ] ; then
-	echo "Usage: $0 <Project Name> <App Name>"
-	exit 1
-fi       
+    echo "Usage: $0 <Project Name> <App Name>"
+    exit 1
+fi
 pname=$1
 appname=$2
 
@@ -64,12 +64,12 @@ find . -type f -exec sed -i "s#\\\$\\\$REDIS_VER\\\$\\\$#$REDIS_VER#g" {} \;
 # Django Version
 find . -type f -exec sed -i "s#\\\$\\\$DJANGO_VER\\\$\\\$#$DJANGO_VER#g" {} \;
 if [ "X$DJANGO_VER" = "X1" ]; then
-	# Default, do nothing
-	echo ""
+    # Default, do nothing
+    echo ""
 elif [ "X$DJANGO_VER" = "X2" ]; then
-	sed -i "s#^Django.*#Django>=2.2,<3.0#" app/.image_files/requirements.txt
+    sed -i "s#^Django.*#Django>=2.2,<3.0#" app/.image_files/requirements.txt
 else
-	sed -i "s#^Django.*#Django=$DJANGO_VER#" app/.image_files/requirements.txt
+    sed -i "s#^Django.*#Django=$DJANGO_VER#" app/.image_files/requirements.txt
 fi
 
 
@@ -86,17 +86,17 @@ convert static/icon.png static/favicon.ico
 
 # Replace/setup our settings file
 cd /dest/$pname/app/$pname
-	# Secret key
+    # Secret key
 sed -i "s/SECRET_KEY =.*/SECRET_KEY = os.getenv('SECRET_KEY', 'NOTaSecret')/" settings.py
-	# DB Settings
+    # DB Settings
 sed -i "s/'ENGINE':.*/'ENGINE': os.getenv('SQL_ENGINE', 'django.db.backends.sqlite3'),/" settings.py
 sed -i "s/'NAME': os.path.join(BASE_DIR, 'db.sqlite3'.*/'NAME': os.getenv('SQL_DATABASE', os.path.join(BASE_DIR, 'db.sqlite3')),\n        'USER': os.getenv('SQL_USER', 'user'),\n        'PASSWORD': os.getenv('SQL_PASSWORD', 'password'),\n        'HOST': os.getenv('SQL_HOST', 'localhost'),\n        'PORT': os.getenv('SQL_PORT', '5432'),/" settings.py
-	# Statics and Media
+    # Statics and Media
 sed -i "s/STATIC_URL =.*/STATIC_URL = '\\/staticfiles\\/'/" settings.py
 sed -i "s/ALLOWED_HOSTS =.*/ALLOWED_HOSTS = [\'*\']/" settings.py
-	# Enable DEBUG environment variable
+    # Enable DEBUG environment variable
 sed -i "s/DEBUG = .*/DEBUG = os.getenv('DEBUG', False)/" settings.py
-	# Enable debug_toolbar app and caches
+    # Enable debug_toolbar app and caches
 sed -i "s/INSTALLED_APPS = .*/INSTALLED_APPS = [\n    'debug_toolbar',  # !BUILD-STRIP/" settings.py
 sed -i "s/MIDDLEWARE = .*/MIDDLEWARE = [\n    'django.middleware.cache.UpdateCacheMiddleware',\n    'debug_toolbar.middleware.DebugToolbarMiddleware',  # !BUILD-STRIP/" settings.py
 sed -i "s/XFrameOptionsMiddleware.*/XFrameOptionsMiddleware',\n    'django.middleware.cache.FetchFromCacheMiddleware',/" settings.py
@@ -125,12 +125,12 @@ CACHES = {
 }
 __EXTRA_SETTINGS__
 
-	# Url mappings for django toolbar
+    # Url mappings for django toolbar
 sed -i "s/import admin.*/import admin\nfrom django.conf.urls import include    # !BUILD-STRIP\nimport debug_toolbar    # !BUILD-STRIP/" urls.py
 if [ "X$DJANGO_VER" = "X1" ]; then
-	echo "urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))   # !BUILD-STRIP" >>urls.py
+    echo "urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))   # !BUILD-STRIP" >>urls.py
 else
-	echo "urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))   # !BUILD-STRIP" >>urls.py
+    echo "urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))   # !BUILD-STRIP" >>urls.py
 fi
 
 # Enable the Entrypoint file that will run the migrations
@@ -152,36 +152,55 @@ docker-compose build
 
 # Rejigger the helm chart
 if [ $CREATE_HELM_CHART = 1 ]; then
-	cd /dest/$pname/charts
-	mv CHART_TEMPLATE $pname
-	mv SAMPLE-PROJECT-master.yaml SAMPLE-${pname}-master.yaml
-	echo "icon: $GURL">> $pname/Chart.yaml
+    cd /dest/$pname/charts
+    mv CHART_TEMPLATE $pname
+    mv SAMPLE-PROJECT-master.yaml SAMPLE-${pname}-master.yaml
+    echo "icon: $GURL">> $pname/Chart.yaml
 else
-	cd /dest/$pname
-	rm -Rf charts
+    cd /dest/$pname
+    rm -Rf charts
 fi
 
 # Create the gitlab project files
 if [ $CREATE_GITLAB_PROJECT != 1 ]; then
-	cd /dest/$pname
-	rm -Rf .flake8 .gitignore .gitlab-ci.yml README.md TODO.md CONTRIBUTING.md CICD_SETUP.md
+    cd /dest/$pname
+    rm -Rf .flake8 .gitignore .gitlab-ci.yml README.md TODO.md CONTRIBUTING.md CICD_SETUP.md
 fi
+
 
 # Create the gitlab project and do an initial commit
 if [ $CREATE_GITLAB_PROJECT = 1 ] && [ "X$GITLAB_HOST" != "X" ] && [ "X$GITLAB_USER" != "X" ] && [ "X$GITLAB_API_TOKEN" != "X" ]; then
-	cd /dest/$pname
-	curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" -X POST "$GITLAB_HOST/api/v4/projects?name=$pname"
-	git init
-	git remote add origin $GITLAB_HOST/$GITLAB_USER/$pname.git
-	git add .
-	if [ $GITLAB_STORE_CREDS = 1 ]; then
-		git config credential.helper store
-	fi
-	git commit -m "Initial commit"
-	git push -u origin master
-	git checkout -b prod
-	git push -u origin prod
-	git checkout master
+    cd /dest/$pname
+    curl --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" -X POST "$GITLAB_HOST/api/v4/projects?name=$pname"
+    cat >>README.md <<__README__
+# $pname  ![pipeline status]($GITLAB_HOST/$GITLAB_USER/$pname/badges/master/pipeline.svg)  ![coverage]($GITLAB_HOST/$GITLAB_USER/$pname/badges/master/coverage.svg?job=django_tests)
+
+This Project was created with opc_django (for better or worse)
+
+## App: $appname
+
+Let me know what this app does!
+__README__
+
+    git init
+    git remote add origin $GITLAB_HOST/$GITLAB_USER/$pname.git
+    git add .
+    if [ $GITLAB_STORE_CREDS = 1 ]; then
+        git config credential.helper store
+    fi
+    git commit -m "Initial commit"
+    git push -u origin master
+    git checkout -b prod
+    git push -u origin prod
+    git checkout master
+    # Add Badges
+    curl -X POST --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
+   --data "name=pipeline&link_url=$GITLAB_HOST/%25%7Bproject_path%7D/-/commit/%25%7Bcommit_sha%7D/pipelines%3Fref=%25%7Bdefault_branch%7D&image_url=$GITLAB_HOST/%25%7Bproject_path%7D/badges/%25%7Bdefault_branch%7D/pipeline.svg" \
+   "$GITLAB_HOST/api/v4/projects/$GITLAB_USER%2F$pname/badges"
+    curl -X POST --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
+   --data "name=coverage&image_url=$GITLAB_HOST/%25%7Bproject_path%7D/badges/%25%7Bdefault_branch%7D/coverage.svg%3Fjob=django_tests&link_url=$GITLAB_HOST" \
+   "$GITLAB_HOST/api/v4/projects/$GITLAB_USER%2F$pname/badges"
+
 fi
 
 
