Updates from usage - Ensure project and app names are lower case, 0-9 and - only - Add "blank password" to dev versions of postgresql and redis - Add password to sample charts so the postgresql password doesn't change on redeploy - Initilize the mediafiles and staticfiles directories

diff --git a/image/opc_create b/image/opc_create
--- a/image/opc_create
+++ b/image/opc_create
@@ -12,12 +12,23 @@ if [ "X$1" = "X" ] ; then
 	exit 1
 fi       
 pname=$1
+echo $pname|grep '[^a-z0-9-]' >/dev/null
+if [ $? = 0 ] ; then
+	echo "Invalid Project Name, must be all lower case, 0-9 and -"
+	exit 1
+fi
 
 if [ "X$2" = "X" ] ; then
 	echo "Usage: $0 <Project Name> <App Name>"
 	exit 1
 fi       
 appname=$2
+echo $appname|grep '[^a-z0-9-]' >/dev/null
+if [ $? = 0 ] ; then
+	echo "Invalid App Name, must be all lower case, 0-9 and -"
+	exit 1
+fi
+
 
 CREATE_HELM_CHART=${CREATE_HELM_CHART:-1}
 
